### ISSUE TITLE
Integrate data into USD pinning file error    -    _pinning_file_generation_funcs.py

### ISSUE THREAD

**Issue by Jeremyball** [ynput/ayon-usd#63]
### Current Behavior:

Trying to publish a simple asset, sphere and cube, fails on **_Integrate data into USD pinning file_**.

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Create geo
2. Create maya USD (use selection and create asset hierarchy)
3. Turn off export animation
4. Publish, error below

### Relevant log output:

```shell
Traceback (most recent call last):
  File "C:\Users\jeremyb\AppData\Local\Ynput\AYON\dependency_packages\ayon_2406251801_windows.zip\dependencies\pyblish\plugin.py", line 528, in __explicit_process
    runner(*args)
  File "C:\Users\jeremyb\AppData\Local\Ynput\AYON\addons\usd_0.1.1\ayon_usd\plugins\publish\integrate_pinning_file.py", line 79, in process
    generate_pinning_file(
  File "C:\Users\jeremyb\AppData\Local\Ynput\AYON\addons\usd_0.1.1\ayon_usd\standalone\usd\pinning\_pinning_file_generation_funcs.py", line 354, in generate_pinning_file
    rootless_pinning_data = remove_root_from_dependency_info(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeremyb\AppData\Local\Ynput\AYON\addons\usd_0.1.1\ayon_usd\standalone\usd\pinning\_pinning_file_generation_funcs.py", line 55, in remove_root_from_dependency_info
    regx = re.compile(pattern)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Autodesk\Maya2025\Python\Lib\re\__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Autodesk\Maya2025\Python\Lib\re\__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Autodesk\Maya2025\Python\Lib\re\_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Autodesk\Maya2025\Python\Lib\re\_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Autodesk\Maya2025\Python\Lib\re\_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Autodesk\Maya2025\Python\Lib\re\_parser.py", line 863, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Autodesk\Maya2025\Python\Lib\re\_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Autodesk\Maya2025\Python\Lib\re\_parser.py", line 539, in _parse
    code = _escape(source, this, state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Autodesk\Maya2025\Python\Lib\re\_parser.py", line 438, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
re.error: bad escape \p at position 8
```

### Additional context:

plugin versions
usd ( 0.1.1 )
maya ( 0.2.12 )

Maya 2025.2

**Comment by BigRoy** [comment]
Thanks @Jeremyball - I can not seem to reproduce it here.

I think I know what the issue in the code - but your setup would need to confirm that. Can you share your configured "roots" for the project? Or provide the output printed from:
```python
import ayon_api
from ayon_core.pipeline import get_current_project_name

print(ayon_api.get_project_roots_by_site_id(get_current_project_name()))
```

I have a feeling you have it configured with backslashes maybe, or with other 'special' characters that may be special to regex patterns.

It'd be nice if you can **also** attach a JSON Publish report from the Publisher UI (you can export that from bottom left in the publisher).

In the meantime, I'll prepare a potential fix.

**Comment by BigRoy** [comment]
@Jeremyball Here's a PR to test at least it passing this particular point: https://github.com/ynput/ayon-usd/pull/64


---

However, looking at the code I think the 'matching' it tries to do against the filename will fail anyway.
@antirotor and @Lypsolon would need to tell me more about how this should work.

At [this point in the code](https://github.com/ynput/ayon-usd/blob/bdf11d2ed35516d133eaa98262b7cfb2ad78792c/client/ayon_usd/standalone/usd/pinning/_pinning_file_generation_funcs.py#L54) the variables for me are:
```
dependency_info={'c:\\projects\\ayontest\\asset\\char_beast\\publish\\usd\\usdAsset\\v007\\ynts_char_beast_usdAsset_v007.usd': 'c:\\projects\\ayontest\\asset\\char_beast\\publish\\usd\\usdAsset\\v007\\ynts_char_beast_usdAsset_v007.usd', 'c:\\projects\\ayontest\\asset\\char_beast\\publish\\usd\\usdAsset\\v007\\payload.usd': 'c:\\projects\\ayontest\\asset\\char_beast\\publish\\usd\\usdAsset\\v007\\payload.usd', 'c:\\projects\\ayontest\\asset\\char_beast\\publish\\usd\\usdAsset_model\\v003\\ynts_char_beast_usdAsset_model_v003.usd': 'c:\\projects\\ayontest\\asset\\char_beast\\publish\\usd\\usdAsset_model\\v003\\ynts_char_beast_usdAsset_model_v003.usd', 'c:\\projects\\ayontest\\asset\\char_beast\\publish\\usd\\usdMain\\v004\\ynts_char_beast_usdMain_v004.usd': 'c:\\projects\\ayontest\\asset\\char_beast\\publish\\usd\\usdMain\\v004\\ynts_char_beast_usdMain_v004.usd', 'c:\\projects\\ayontest\\asset\\char_beast\\publish\\usd\\usdAsset_rig\\v003\\ynts_char_beast_usdAsset_rig_v003.usd': 'c:\\projects\\ayontest\\asset\\char_beast\\publish\\usd\\usdAsset_rig\\v003\\ynts_char_beast_usdAsset_rig_v003.usd', 'c:\\projects\\ayontest\\asset\\char_beast\\publish\\rig\\rigMain\\v004\\ynts_char_beast_rigMain_v004.usd': 'c:\\projects\\ayontest\\asset\\char_beast\\publish\\rig\\rigMain\\v004\\ynts_char_beast_rigMain_v004.usd', 'c:\\projects\\ayontest\\asset\\char_beast\\publish\\rig\\rigMain\\v004\\ynts_char_beast_rigMain_v004.ma': 'c:\\projects\\ayontest\\asset\\char_beast\\publish\\rig\\rigMain\\v004\\ynts_char_beast_rigMain_v004.ma'}
root_info={'work': 'C:/projects'}
replacements={'C:/projects': 'work'}
pattern='(C:/projects)'
```

As you can see - the regex doesn't match it - and hence my pinning file does NOT contain rootless keys @Lypsolon @antirotor 

---

Also @antirotor I'm quite sure we don't want the pinning file to be generated for EACH USD file, right? Only for renders? or?

**Comment by Jeremyball** [comment]
Hey, thanks for the quick response. Attached publish report

Print out:
{'work': 'E:\\AYON\\projects'}

[publish-report-241004-09-22.json](https://github.com/user-attachments/files/17249718/publish-report-241004-09-22.json)

**Comment by BigRoy** [comment]
> {'work': 'E:\AYON\projects'}

Thanks, that confirms it:
```python
import re

re.compile(r"E:\AYON\projects")
# Error: error: file C:\Program Files\Autodesk\Maya2025\Python\Lib\re\_parser.py line 438: bad escape \p at position 7
```

```python
import re

pattern = re.escape(r"E:\AYON\projects")
print(pattern)  # prints: E:\\AYON\\projects
re.compile(pattern)
```

So my PR should at least allow you to continue - or if hard for you to update and deploy yourself, otherwise change your path in settings to use forward slashes, like: `E:/AYON/projects`.

**Comment by Jeremyball** [comment]
For now I will reconfigure with forward slashes.  Thanks!
